version: "3.3"

services:
  pinebot:
    image: pinebot:latest
    volumes:
    # Local Data
    - pinebot-data:/data
    # Docker Socket Data
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/usr/bin/docker:/usr/bin/docker"
    - "/usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02"
    # Timezone persistance
    - "/etc/timezone:/etc/timezone:ro" 
    - "/etc/localtime:/etc/localtime:ro"
    environment:
    - TOKEN=${TOKEN} # Bot Access Token
    - DATABASE_STRING=${DATABASE_STRING} # Database connection address & pswd
    restart: always
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.19"
      
      # RCON (Required for sending commands)
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCONPASS}"
      RCON_PORT: 25575
    volumes:
    - minecraft-data:/data
    restart: unless-stopped
volumes:
  pinebot-data:
    external: false
  minecraft-data:
    external: false
